# -*- coding: utf-8 -*-
"""felzenszwalb graph-based segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bwjE06ObHIuSfhOPnlmiB2FSC3_sbfVI
"""

from google.colab import drive
drive.mount('/content/drive')
from skimage.segmentation import felzenszwalb
from skimage.segmentation import mark_boundaries
from PIL import Image
import matplotlib.pyplot as plt


img = Image.open('/content/drive/MyDrive/cs195_sp22/lab2_input_image/seal.jpg')
segments = felzenszwalb(img, scale=32, sigma=0.95, min_size=800)
plt.imshow(mark_boundaries(img,segments, color=(1,0,0)))
plt.title('Felzenswalb graph-based segmentation')